### ISSUE TITLE
[Feature Request] Add elementary dark variant into the themes

### ISSUE THREAD

**Issue by validatedev** [flathub/org.gtk.Gtk3theme.elementary#5]
## Linux distribution and version
elementary OS 5.1.2 Hera
## Flatpak version
Flatpak 1.6.2
## Description of the problem
Well, there is a theme `org.gtk.Gtk3theme.elementary`, but not `org.gtk.Gtk3theme.elementary-dark`. I'm using the dark variant of the elementary theme all over the system.
## Steps to reproduce
Use dark variant of the elementary theme
Open any app (e.g. Geary)
You can see that it doesn't apply on the Geary

**Comment by TingPing** [comment]
As far as I can tell `elementary-dark` doesn't exist.

https://github.com/elementary/stylesheet/tree/master/elementary/gtk-3.0

**Comment by validatedev** [comment]
> As far as I can tell `elementary-dark` doesn't exist.
> 
> https://github.com/elementary/stylesheet/tree/master/elementary/gtk-3.0

I don’t think the theme is a seperate package. Here’s the info that how the dark variant can be applied:

> You'll have to create the file: ` ~/.config/gtk-3.0/settings.ini`
And add these two lines:
`[Settings] `
` gtk-application-prefer-dark-theme=1 `
Log out and log in.

**Comment by TingPing** [comment]
Well that isn't useful for sandboxed applications, and elementary knows that, so if they make a real dark theme it can be packaged.

**Comment by validatedev** [comment]
I hope they will see the problem soon then.

**Comment by cassidyjames** [comment]
The dark variant of the elementary stylesheet isn't currently intended to be general purpose and apply to all apps, so there aren't plans to package it as a separate stylesheet. Instead, apps can request a dark variant if they support it and in that case, it will use the dark variant.

If a freedesktop dark preference is implemented on elementary OS (and possibly GTK and GNOME), then this might make more sense. But at the moment, we don't plan to package it up separately.
