### ISSUE TITLE
Update for Eos 6.0 Odin

### ISSUE THREAD

**Issue by mikesnoeren** [flathub/org.gtk.Gtk3theme.elementary#6]
With Eos 6.0 being released and having its main focus on flathub apps it would be nice if flathub had a matching gtk version (and support for darkmode!).

Check below for current versions:
![image](https://user-images.githubusercontent.com/52166423/129034783-51a5af6d-3645-476f-92b0-ccd3675b53af.png)

**Comment by TingPing** [comment]
So sadly elementary made like 10 themes. So there is a decent chunk of work making 10 new packages.

**Comment by TingPing** [comment]
Turns out the name `org.gtk.Gtk3theme.io.elementary.stylesheet.banana` is an invalid flatpak extension, so currently all of these themes cannot be packaged.

**Comment by TingPing** [comment]
https://github.com/elementary/stylesheet/issues/1072

**Comment by TingPing** [comment]
https://github.com/flatpak/flatpak/pull/4366

**Comment by mikesnoeren** [comment]
Are there any plans or steps to resolve this issue, other than having all Flatpak app authors opt-into the elementary Platform?

I think the majority of Flatpak apps authors don't care about specific OS needs and therefore will not opt-into nor ship with the default eOS stylesheets. Afterall, I was made aware that all Flatpak apps are supposed to work out of the box on every major OS.

If this package doesn't get fixed, 80% of my apps feel off. That unfortunately is a dealbreaker for me.

**Comment by TingPing** [comment]
I don't have more time to commit to it. The theme names are just problematic...
